# Generated by Django 5.1.2 on 2024-11-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_post_author_post_createdtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("password", models.CharField(max_length=50)),
                ("createdTime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("videoURL", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=50)),
                ("createdTime", models.DateTimeField()),
            ],
        ),
    ]
