# Generated by Django 5.1 on 2024-11-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_videopost"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUserVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("verificationCode", models.CharField(max_length=6)),
                ("createdTime", models.DateTimeField()),
            ],
        ),
    ]
