# Generated by Django 5.1 on 2024-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_emailuserverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostUserLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdTime", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="VideoPost",
        ),
        migrations.AddField(
            model_name="post",
            name="likedCount",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="postType",
            field=models.CharField(default="blog", max_length=20),
            preserve_default=False,
        ),
    ]
