# Generated by Django 5.1 on 2024-11-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_postuserlike_delete_videopost_post_likedcount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postuserlike",
            name="post",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.post"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postuserlike",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="postuserlike",
            unique_together={("post", "user")},
        ),
    ]
