# Generated by Django 5.1.2 on 2024-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_postuserlike_post_postuserlike_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskType", models.CharField(max_length=20)),
                ("taskName", models.CharField(max_length=100)),
                ("taskUser", models.CharField(max_length=50)),
                ("taskCreateTime", models.DateTimeField()),
                ("taskDeadline", models.DateTimeField()),
            ],
        ),
    ]
