# Generated by Django 5.1 on 2025-02-10 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_task_completed_task_completeddatetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("datatype", models.CharField(max_length=10)),
                ("water_intake", models.IntegerField(help_text="Water intake in ml")),
                (
                    "calorie_intake",
                    models.IntegerField(help_text="Calorie intake in kcal"),
                ),
                (
                    "heart_rate",
                    models.IntegerField(help_text="Average heart rate in bpm"),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
    ]
