# Generated by Django 5.1 on 2025-02-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_healthdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthdata",
            old_name="username",
            new_name="user",
        ),
    ]
