# Generated by Django 5.1 on 2025-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_rename_username_healthdata_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthdata",
            name="date",
            field=models.DateField(),
        ),
    ]
