# Generated by Django 5.1 on 2025-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_healthdata_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdata",
            name="run_distance",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
