# Generated by Django 5.1 on 2025-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_healthdata_run_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.FloatField(
                default=1, help_text="amount of time to complete in hours"
            ),
            preserve_default=False,
        ),
    ]
