# Generated by Django 5.1.2 on 2024-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=50)),
                ("createdTime", models.DateTimeField()),
            ],
        ),
    ]
